config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do 
  end

    devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_out_path_for(resource)
    'http://localhost:3000/'    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def show

  end
  

  def create
    Post.create(post_params)
    redirect_to 'http://localhost:3000/'
  end

  def destroy
    post = Post.find(params[:id])
    if post.user_id == current_user.id
       post.destroy 
       redirect_to("http://localhost:3000/")
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(content: params[:content])
    redirect_to("http://localhost:3000/")
  end
  
  private
   def post_params
     params.require(:post).permit(:content).merge(user_id:current_user.id)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mini-blog</title>
  <style type="text/css" href="application.css"></style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
</head>
<body>

<nav class="#4db6ac teal lighten-2">
  <div class="nav-wrapper">
    <a href="http://localhost:3000/" class="brand-logo center" >mini app</a>

    <% if user_signed_in? %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a class="#" href="/posts/new">New</a></li>
      <li><%= link_to "Sign Out ", destroy_user_session_path, method: :delete %><li>
    </ul>
  </div>

    <% else %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Sign In", new_user_session_path%><li>
      <li><%= link_to "Sign Up", new_user_registration_path%><li>
    </div>
 <% end %>

</nav>

<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div class="row">
    <div class="col s12 m6 offset-m3">
      <div class="card #fffde7 yellow lighten-5">
        <div class="card-content black-text">
          <p><%= post.content %></p>
        </div>

        <% if user_signed_in?  && current_user.id == post.user_id %>
        <div class="card-action">
          <%= link_to 'EDIT', "/posts/#{post.id}/edit", method: :get %>
          <%= link_to 'DELETE', "/posts/#{post.id}", method: :delete %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/edit.html.erb
<%= form_with url: post_path, method: :patch, local: true do |f| %>
  <%= f.text_area :content %>
  <%= f.submit%>
<% end %>

app/views/posts/index.html.erb
 <div class="contents row">
  <% @posts.each do |post| %>
     <%= render partial: "post",locals:{ post: post} %>
    <% end %>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
 
  <div class="field">
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "POST" %>
  </div>
<% end %>